version: '3.3'
services:
  dydx:
    cpus: 12
    mem_limit: 64GB
    image: nodefleet/dydx:v1.0.1
    container_name: dydx
    restart: unless-stopped
    volumes:
      - './config/:/dydxprotocol/.dydxprotocol/config/'
      - './data/:/dydxprotocol/.dydxprotocol/data/'
    ports:
      - '1317:1317'
      - '26657:26657'
      - '9090:9090'
    expose:
      - 26660
      - 26667
    env_file:
    - .env
