version: '3.3'
services:
  dydx:
    cpus: 12
    mem_limit: 64GB
    image: nodefleet/dydx:v1.0.1
    container_name: dydx
    restart: unless-stopped
    volumes:
      - './config/:/dydxprotocol/.dydxprotocol/config/'
      - './data/:/dydxprotocol/.dydxprotocol/data/'
    ports:
      - '1317:1317'
      - '26657:26657'
      - '9090:9090'
    expose:
      - 26660
      - 26667
    env_file:
    - .env

  traefik:
    cpus: 4
    mem_limit: 16G
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80       
      - 443:443 
      #- 8082:8082 #For prometheus metrics (OPTIONAL)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yaml:/traefik.yml:ro
      - ./traefik/services/:/etc/traefik/services/:ro
      - ./traefik/certs:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.insecure=true
